// Curated study lists (by problem slug). Unknown slugs are dropped at load time.
export const STUDY_LISTS = [
  {
    id: 'blind-75', name: 'Blind 75', description: 'The classic 75 must-do interview problems.',
    slugs: [
      'two-sum', 'best-time-to-buy-and-sell-stock', 'contains-duplicate', 'product-of-array-except-self', 'maximum-subarray', 'maximum-product-subarray', 'find-minimum-in-rotated-sorted-array', 'search-in-rotated-sorted-array', '3sum', 'container-with-most-water',
      'sum-of-two-integers', 'number-of-1-bits', 'counting-bits', 'missing-number', 'reverse-bits',
      'climbing-stairs', 'coin-change', 'longest-increasing-subsequence', 'longest-common-subsequence', 'word-break', 'combination-sum-iv', 'house-robber', 'house-robber-ii', 'decode-ways', 'unique-paths', 'jump-game',
      'clone-graph', 'course-schedule', 'pacific-atlantic-water-flow', 'number-of-islands', 'longest-consecutive-sequence', 'alien-dictionary', 'graph-valid-tree', 'number-of-connected-components-in-an-undirected-graph',
      'insert-interval', 'merge-intervals', 'non-overlapping-intervals', 'meeting-rooms', 'meeting-rooms-ii',
      'reverse-linked-list', 'linked-list-cycle', 'merge-two-sorted-lists', 'merge-k-sorted-lists', 'remove-nth-node-from-end-of-list', 'reorder-list',
      'set-matrix-zeroes', 'spiral-matrix', 'rotate-image', 'word-search',
      'longest-substring-without-repeating-characters', 'longest-repeating-character-replacement', 'minimum-window-substring', 'valid-anagram', 'group-anagrams', 'valid-parentheses', 'valid-palindrome', 'longest-palindromic-substring', 'palindromic-substrings', 'encode-and-decode-strings',
      'maximum-depth-of-binary-tree', 'same-tree', 'invert-binary-tree', 'binary-tree-maximum-path-sum', 'binary-tree-level-order-traversal', 'serialize-and-deserialize-binary-tree', 'subtree-of-another-tree', 'construct-binary-tree-from-preorder-and-inorder-traversal', 'validate-binary-search-tree', 'kth-smallest-element-in-a-bst', 'lowest-common-ancestor-of-a-binary-search-tree', 'implement-trie-prefix-tree', 'design-add-and-search-words-data-structure', 'word-search-ii',
      'merge-k-sorted-lists', 'top-k-frequent-elements', 'find-median-from-data-stream',
    ],
  },
  {
    id: 'top-interview-150', name: 'Top Interview (starter)', description: 'A broad warm-up set across every topic, ordered from easy to hard.',
    slugs: [
      'merge-sorted-array', 'remove-element', 'remove-duplicates-from-sorted-array', 'majority-element', 'rotate-array', 'best-time-to-buy-and-sell-stock-ii', 'jump-game-ii', 'h-index', 'insert-delete-getrandom-o1', 'gas-station', 'candy', 'trapping-rain-water',
      'roman-to-integer', 'integer-to-roman', 'length-of-last-word', 'longest-common-prefix', 'reverse-words-in-a-string', 'zigzag-conversion', 'find-the-index-of-the-first-occurrence-in-a-string', 'text-justification',
      'is-subsequence', 'two-sum-ii-input-array-is-sorted', 'minimum-size-subarray-sum', 'substring-with-concatenation-of-all-words',
      'valid-sudoku', 'game-of-life', 'ransom-note', 'isomorphic-strings', 'word-pattern', 'happy-number', 'contains-duplicate-ii', 'summary-ranges',
      'min-stack', 'evaluate-reverse-polish-notation', 'basic-calculator', 'simplify-path',
      'add-two-numbers', 'copy-list-with-random-pointer', 'reverse-linked-list-ii', 'reverse-nodes-in-k-group', 'remove-duplicates-from-sorted-list-ii', 'rotate-list', 'partition-list', 'lru-cache',
      'symmetric-tree', 'populating-next-right-pointers-in-each-node-ii', 'flatten-binary-tree-to-linked-list', 'path-sum', 'sum-root-to-leaf-numbers', 'binary-search-tree-iterator', 'count-complete-tree-nodes', 'binary-tree-right-side-view', 'average-of-levels-in-binary-tree', 'binary-tree-zigzag-level-order-traversal', 'minimum-absolute-difference-in-bst',
      'surrounded-regions', 'evaluate-division', 'course-schedule-ii', 'snakes-and-ladders', 'minimum-genetic-mutation', 'word-ladder',
      'letter-combinations-of-a-phone-number', 'combinations', 'permutations', 'combination-sum', 'n-queens-ii', 'generate-parentheses',
      'convert-sorted-array-to-binary-search-tree', 'sort-list', 'maximum-subarray', 'kth-largest-element-in-an-array', 'ipo', 'find-k-pairs-with-smallest-sums',
      'add-binary', 'reverse-bits', 'single-number', 'bitwise-and-of-numbers-range', 'palindrome-number', 'plus-one', 'factorial-trailing-zeroes', 'sqrtx', 'powx-n', 'max-points-on-a-line',
      'triangle', 'minimum-path-sum', 'unique-paths-ii', 'longest-palindromic-substring', 'interleaving-string', 'edit-distance', 'best-time-to-buy-and-sell-stock-iii', 'best-time-to-buy-and-sell-stock-iv', 'maximal-square',
    ],
  },
  {
    id: 'neetcode-core', name: 'NeetCode-style core', description: 'Pattern-by-pattern coverage: arrays, two pointers, sliding window, stack, binary search, linked list, trees, tries, heaps, backtracking, graphs, DP.',
    slugs: [
      'contains-duplicate', 'valid-anagram', 'two-sum', 'group-anagrams', 'top-k-frequent-elements', 'product-of-array-except-self', 'valid-sudoku', 'longest-consecutive-sequence',
      'valid-palindrome', 'two-sum-ii-input-array-is-sorted', '3sum', 'container-with-most-water', 'trapping-rain-water',
      'best-time-to-buy-and-sell-stock', 'longest-substring-without-repeating-characters', 'longest-repeating-character-replacement', 'permutation-in-string', 'minimum-window-substring', 'sliding-window-maximum',
      'valid-parentheses', 'min-stack', 'evaluate-reverse-polish-notation', 'generate-parentheses', 'daily-temperatures', 'car-fleet', 'largest-rectangle-in-histogram',
      'binary-search', 'search-a-2d-matrix', 'koko-eating-bananas', 'find-minimum-in-rotated-sorted-array', 'search-in-rotated-sorted-array', 'time-based-key-value-store', 'median-of-two-sorted-arrays',
      'reverse-linked-list', 'merge-two-sorted-lists', 'reorder-list', 'remove-nth-node-from-end-of-list', 'copy-list-with-random-pointer', 'add-two-numbers', 'linked-list-cycle', 'find-the-duplicate-number', 'lru-cache', 'merge-k-sorted-lists', 'reverse-nodes-in-k-group',
      'invert-binary-tree', 'maximum-depth-of-binary-tree', 'diameter-of-binary-tree', 'balanced-binary-tree', 'same-tree', 'subtree-of-another-tree', 'lowest-common-ancestor-of-a-binary-search-tree', 'binary-tree-level-order-traversal', 'binary-tree-right-side-view', 'count-good-nodes-in-binary-tree', 'validate-binary-search-tree', 'kth-smallest-element-in-a-bst', 'construct-binary-tree-from-preorder-and-inorder-traversal', 'binary-tree-maximum-path-sum', 'serialize-and-deserialize-binary-tree',
      'implement-trie-prefix-tree', 'design-add-and-search-words-data-structure', 'word-search-ii',
      'kth-largest-element-in-a-stream', 'last-stone-weight', 'k-closest-points-to-origin', 'kth-largest-element-in-an-array', 'task-scheduler', 'design-twitter', 'find-median-from-data-stream',
      'subsets', 'combination-sum', 'permutations', 'subsets-ii', 'combination-sum-ii', 'word-search', 'palindrome-partitioning', 'letter-combinations-of-a-phone-number', 'n-queens',
      'number-of-islands', 'clone-graph', 'max-area-of-island', 'pacific-atlantic-water-flow', 'surrounded-regions', 'rotting-oranges', 'course-schedule', 'course-schedule-ii', 'redundant-connection', 'word-ladder',
      'network-delay-time', 'min-cost-to-connect-all-points', 'swim-in-rising-water', 'cheapest-flights-within-k-stops',
      'climbing-stairs', 'min-cost-climbing-stairs', 'house-robber', 'house-robber-ii', 'longest-palindromic-substring', 'palindromic-substrings', 'decode-ways', 'coin-change', 'maximum-product-subarray', 'word-break', 'longest-increasing-subsequence', 'partition-equal-subset-sum',
      'unique-paths', 'longest-common-subsequence', 'best-time-to-buy-and-sell-stock-with-cooldown', 'coin-change-ii', 'target-sum', 'interleaving-string', 'longest-increasing-path-in-a-matrix', 'distinct-subsequences', 'edit-distance', 'burst-balloons', 'regular-expression-matching',
      'maximum-subarray', 'jump-game', 'jump-game-ii', 'gas-station', 'hand-of-straights', 'merge-triplets-to-form-target-triplet', 'partition-labels', 'valid-parenthesis-string',
      'insert-interval', 'merge-intervals', 'non-overlapping-intervals', 'minimum-interval-to-include-each-query',
      'rotate-image', 'spiral-matrix', 'set-matrix-zeroes', 'happy-number', 'plus-one', 'powx-n', 'multiply-strings', 'detect-squares',
      'single-number', 'number-of-1-bits', 'counting-bits', 'reverse-bits', 'missing-number', 'sum-of-two-integers', 'reverse-integer',
    ],
  },
];
